server:
  port: 8080

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: mandy_Test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.5.4:3306/top?useSSL=false
    username: mandy
    password: 123456

mybatis:
  type-aliases-package: com.test.model
  mapper-locations:
    - mapper/*


